### PR TITLE
[WIP]: AminoAcid k-mer and minhash

### PR DESCRIPTION
**Pull request by harryscholes**
Please do not merge yet.

## Types of changes

This PR implements the following changes:
_(Please tick any or all of the following that are applicable)_

* [x] :sparkles: New feature (A non-breaking change which adds functionality).
* [ ] :bug: Bug fix (A non-breaking change, which fixes an issue).
* [ ] :boom: Breaking change (fix or feature that would cause existing functionality to change).

## :clipboard: Additional detail

- If you have implemented new features or behaviour
  - **Provide a description of the addition** in as many details as possible.
This PR adds:
    - The `AminoAcidKmer` type
    - Implements an iterator for `AminoAcidSequence`
    - Implements `minhash` for `AminoAcidSequence`

  - **Provide a runnable example of use of your addition**. This lets reviewers
    and others try out the feature before it is merged or makes it's way to release.

```julia
using BioSequences
seq = randaaseq(300)
minhash(seq, 8, 20)
```

## :ballot_box_with_check: Checklist

- [x] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/stable/manual/style-guide/).
- [ ] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/stable/manual/documentation/).
- [ ] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [ ] :ok: There are unit tests that cover the code changes I have made.
- [x] :ok: The unit tests cover my code changes AND they pass.
- [ ] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- [x] :ok: All changes should be compatible with the latest stable version of Julia.
- [ ] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by kescobo** [comment]
I'm excited about this! Let us know when it's ready for review.

**Comment by BenJWard** [comment]
Thanks for taking the time to do this @harryscholes.

I'm working on a v2.0 of BioSequences right now that updates a lot of the API and restructures the module, and Kmers are getting an overhaul. Some of the change you introduce here such as the Abstract Kmer type is very similar to some of the changes to kmers I've made on the `version2` branch.

Would you want to see about whether these changes can be reconciled with version2 and merged with that branch rather than master? This could be yet another major feature addition around the kmers v2 will introduce.

**Comment by harryscholes** [comment]
Hi Ben, I've just managed to take a look at the new k-mer code in v2.0.0. It's looking really good.

My main motivation for having a stab at implementing all of this was to be able to minhash `AminoAcidSequence`s. I guess before I think about merging in the `AminoAcidKmer` and minhashing, we need to decide on a good way to represent amino acid k-mers. There probably is a simpler way of implementing `minhash(::AminoAcidSequence)` that doesn't require the `AminoAcidKmer` type.

I implemented `AminoAcidKmer` as a simple container holding an `AminoAcidSequence`. I see the benefit of having nucleic acid k-mer types because you can fit a lot of information into a small amount of memory, but I'm not sure about the `AminoAcidKmer`.

**Comment by jakobnissen** [comment]
@harryscholes I think this PR may be oudated - can it be closed?
For what it's worth, we've had some progress on this front. Kmers are undergoing (yet another) overhaul - the current overhaul is supposed to make them such that they are to a `LongSequence` what a static array is to a vector. That is, an arbitrary-length stack-allocated alphabet-agnostic biosequence with compiletime length.

MinHashing has been implmented in MinHash.jl. However, we might want a kmer minhashing package which combines BioSequences.jl, MinHash.jl and Kmers.jl to create a high-performance generic kmer minhash library.

**Comment by harryscholes** [comment]
Yes this can be closed

**Pull request closed without merging**
