### PR TITLE
Allow translate(seq) to take a DNASequence

### PR DESCRIPTION
**Pull request by kdyrhage**
# Allow translate(seq) to take a DNASequence
Currently `translate(seq::DNASequence)` throws a MethodError. While `translate(convert(RNASequence, seq))` might make sense biologically, it is unnecessarily verbose. I propose doing this conversion automatically.

## Types of changes

This PR implements the following changes:

* [x] :sparkles: New feature (A non-breaking change which adds functionality).
* [ ] :bug: Bug fix (A non-breaking change, which fixes an issue).
* [ ] :boom: Breaking change (fix or feature that would cause existing functionality to change).

## :ballot_box_with_check: Checklist

- [x] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/stable/manual/style-guide/).
- [x] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/stable/manual/documentation/).
- [x] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [x] :ok: There are unit tests that cover the code changes I have made.
- [x] :ok: The unit tests cover my code changes AND they pass.
- [x] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- [x] :ok: All changes should be compatible with the latest stable version of Julia.
- [x] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by kdyrhage** [comment]
Sounds like a good idea. There is no method for `translate(::BioSequence{RNAAlphabet{2}})` either, though, so I'm adding that as well.

Something else I was thinking of is adding a keyword argument for changing alternative start codons to `AA_M`. `ncbi_trans_table` doesn't contain this information, so the easiest thing would be to just always change the first amino acid if the flag is set. Something like `convert_start_codon::Bool=false`. How does that sound?

**Comment by BenJWard** [comment]
Why do you want to convert the first codon to AA_M?

**Comment by kdyrhage** [comment]
Because alternative start codons in bacteria are still recognised by fMet-tRNA, not by whatever tRNA they are usually recognised by.

**Comment by BenJWard** [comment]
@kdyrhage All the boxes are ticked, and CI is running. When it passes I'm happy to merge this, unless there is anything else furthur that you want to do.

**Pull request merged**
