### PR TITLE
🐛 in iscanonical / canonical

### LINKED ISSUE #225: 🐛 in iscanonical / canonical
Consider these two codons, both RC of each other:

```
a = dna"TCA"
b = dna"TGA"
```

The first one is the canonical, as a < b, as `DNA_C < DNA_G`

However,

```
julia> iscanonical(dna"TCA")
true

julia> iscanonical(dna"TGA")
true
```

And so, `canonical` will return the input sequence for both of these.

### PR DESCRIPTION
**Pull request by SabrinaJaye**
Fixes #225

## :ballot_box_with_check: Checklist

- [x] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/v1/manual/style-guide/).
- [x] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/v1/manual/documentation/).
- [x] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [x] :ok: There are unit tests that cover the code changes I have made.
- [x] :ok: The unit tests cover my code changes AND they pass.
- [ ] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- [ ] :ok: All changes should be compatible with the latest stable version of Julia.
- [ ] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by jakobnissen** [comment]
Wouldn't it work to just check if i <= j instead of <?

**Comment by SabrinaJaye** [comment]
Does it not need to continue comparing elements past the halfway point?

**Comment by jakobnissen** [comment]
Nope

**Comment by SabrinaJaye** [comment]
@JuliaRegistrator register

**Review by kescobo — APPROVED** [review]

**Comment by SabrinaJaye** [comment]
Gonna close this and do the 3.0.1 release again - accidentally slurped up some changes into it that would be a minor increment, rather than a patch increment.

**Pull request closed without merging**
