### PR TITLE
Version 3 updates

### PR DESCRIPTION
**Pull request by SabrinaJaye**
## Types of changes

This PR implements the following changes:
_(Please tick any or all of the following that are applicable)_

* [ ] :sparkles: New feature (A non-breaking change which adds functionality).
* [ ] :bug: Bug fix (A non-breaking change, which fixes an issue).
* [x] :boom: Breaking change (fix or feature that would cause existing functionality to change).

## :ballot_box_with_check: Checklist

- [ ] :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/v1/manual/style-guide/).
- [ ] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/v1/manual/documentation/).
- [ ] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- [ ] :ok: There are unit tests that cover the code changes I have made.
- [ ] :ok: The unit tests cover my code changes AND they pass.
- [ ] :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- [ ] :ok: All changes should be compatible with the latest stable version of Julia.
- [ ] :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by jakobnissen** [comment]
How on Earth does this have _lower_ test coverage than v2? I can do another pass of testing if you want.

**Comment by SabrinaJaye** [comment]
Did a manual merge into master because doing rebase to get rid of the conflicts was getting a bit nerve itching.

**Comment by SabrinaJaye** [comment]
@jakobnissen can you check the longsequences/indexing.jl as there was a merge conflict where master had a whole lot more methods at the bottom of the file for Base.setindex and such for SeqOrView, that v3 didn't have. I opted to keep them as if they were meant to go, we can delete them again, rather than throw something that was part of a patch update.

**Comment by jakobnissen** [comment]
Sure thing. I'll take a look tomorrow!

**Pull request closed without merging**
