### PR TITLE
use Dict to store counts in Composition

### PR DESCRIPTION
**Pull request by bicycle1885**
This is a little bit slower than using Vector but it is able to store
counts of long k-mers with far less memory.

### CODE REVIEW

**Comment by Ward9250** [comment]
Could we have both versions? Unified by an API and abstract type, and then the best one for the use case applied?

**Comment by bicycle1885** [comment]
We can, but I don't think it is a good idea since it makes the code more complicated. The new data structure I propose is still fast in most cases and the counting algorithm is not changed. So, the performance of `composition` does not change for `BioSequence`s:

master:
```
julia> @benchmark composition($seq)
BenchmarkTools.Trial:
  memory estimate:  224 bytes
  allocs estimate:  2
  --------------
  minimum time:     27.222 μs (0.00% GC)
  median time:      29.200 μs (0.00% GC)
  mean time:        30.333 μs (0.00% GC)
  maximum time:     212.823 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

```

this branch:
```
julia> @benchmark composition($seq)
BenchmarkTools.Trial:
  memory estimate:  800 bytes
  allocs estimate:  10
  --------------
  minimum time:     27.721 μs (0.00% GC)
  median time:      28.023 μs (0.00% GC)
  mean time:        30.111 μs (0.00% GC)
  maximum time:     137.682 μs (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1

```

The difference gets large for `Kmer`s but using `composition` for a `Kmer` value is not best in terms of performance because it does some allocation. Using `count_{a,c,g,t}` is the best choice in that case.

master:
```
julia> @benchmark composition(kmer"ACGTAGTA")
BenchmarkTools.Trial:
  memory estimate:  224 bytes
  allocs estimate:  2
  --------------
  minimum time:     42.198 ns (0.00% GC)
  median time:      46.022 ns (0.00% GC)
  mean time:        54.982 ns (11.49% GC)
  maximum time:     1.431 μs (86.91% GC)
  --------------
  samples:          10000
  evals/sample:     987

julia> @benchmark BioSequences.count_a(kmer"ACGTAGTA")
BenchmarkTools.Trial:
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     1.896 ns (0.00% GC)
  median time:      2.050 ns (0.00% GC)
  mean time:        2.210 ns (0.00% GC)
  maximum time:     35.214 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000

```

this branch:
```
julia> @benchmark composition(kmer"ACGTAGTA")
BenchmarkTools.Trial:
  memory estimate:  592 bytes
  allocs estimate:  9
  --------------
  minimum time:     255.330 ns (0.00% GC)
  median time:      271.447 ns (0.00% GC)
  mean time:        322.011 ns (9.04% GC)
  maximum time:     6.661 μs (85.65% GC)
  --------------
  samples:          10000
  evals/sample:     352

```

**Comment by Ward9250** [comment]
That sounds fair enough. Perhaps I should have a look at using Composition with the fast pairwise counting mechanism I built.

**Comment by Ward9250** [comment]
If I dict is used for the composition, is there any point to the wrapping associative type anymore? It original purpose seems to be to act like a dict, but using a vector underneath, now a dict is used underneath, is there a point to the wrapping type anymore?

**Comment by bicycle1885** [comment]
Yeah, that makes sense, but the semantic is significantly different from dicts. For example, `getindex` is overloaded to return zero for non-exist elements, which is similar to `DefautDict` of DataStructures.jl. Also, `merge` adds two counts instead of overwriting the former with the latter. `Composition` is convertible to `Dict`, too.

**Comment by Ward9250** [comment]
I'm convinced! 😆  Look forward to the merge!!

**Pull request merged**
