### PR TITLE
[Review] Drop Julia 0.5

### PR DESCRIPTION
**Pull request by Ward9250**

### CODE REVIEW

**Comment by Ward9250** [comment]
Yeah I know I'm still WIP on it. 👍

**Comment by bicycle1885** [comment]
I thought so, but just in case. I think updating the CI settings is the last thing before merging it.

BTW, I tagged BioSymbols.jl v1.2.0 including latest changes (https://github.com/JuliaLang/METADATA.jl/pull/10429).

**Comment by Ward9250** [comment]
Awesome! 🎉

**Comment by Ward9250** [comment]
Ok this is looking ready now. There are a couple of methods in the source which I wonder if they need to be parametric or not, as the type of sequence does not need to be constrained - the alphabet is left as 'A', and the 'A' then is not used in the method body, but we could always remove those later, the syntax is updated and works :+1:

**Comment by Ward9250** [comment]
I'll merge and tag when the latest checks have gone through.

**Pull request merged**
